apiVersion: v1
kind: Service

metadata:
  name: jenkins-eks-demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

spec:
  type: LoadBalancer

  selector:
    app: jenkins-eks-demo

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000